### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by dotlambda** [OpenMandrivaAssociation/maui-core#1]
Where did you obtain the license information from? Upstream doesn't ship a license file. See https://github.com/Nitrux/maui-core/issues/1.
cc @AngryPenguinPL

**Comment by berolinux** [comment]
The license for the whole package seems to be missing indeed, but there are files indicating the intended license in the subdirectories containing most of the relevant code.

https://github.com/Nitrux/maui-core/blob/main/libs/audio/README.md
https://github.com/Nitrux/maui-core/blob/main/libs/notifications/README.md

The only larger piece of code that doesn't have an obvious license attached to it inside the repository is libs/power.

However, given that it is part of Maui, and https://mauikit.org/ states that it is "LGPL 3 Licensed" and
"MauiKit is a free and open-source project, and you can use, copy, merge, publish, and distribute the framework without significant limitations.", it is safe to assume (to the point that we believe it would hold up in court) that it is openly licensed.

It would be nice to have this clarified upstream, but in the mean time, there doesn't seem to be a need to remove the package.

**Comment by dotlambda** [comment]
> it is safe to assume (to the point that we believe it would hold up in court) that it is openly licensed

But maui-core is pretty much independent from mauikit. It's just a dependency of maui-shell.
